/* Generated by AN DISI Unibo */ 
package it.unibo.butler_pathfinder_handler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Butler_pathfinder_handler ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('locationIndex.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("wait") { //this:State
					action { //it:State
					}
					 transition(edgeName="t011",targetState="actionPipeline",cond=whenDispatch("action"))
					transition(edgeName="t012",targetState="assertMove",cond=whenDispatch("goalReached"))
				}	 
				state("actionPipeline") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("action(ARG0,ARG1,ARG2,ARG3,ARG4)"), Term.createTerm("action(_,_,_,_,_)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								forward("action", "action(${payloadArg(0)},${payloadArg(1)},${payloadArg(2)},${payloadArg(3)},${payloadArg(4)})" ,"butler_pathfinder_handler" ) 
						}
					}
					 transition(edgeName="t013",targetState="handleMovement",cond=whenDispatch("action"))
				}	 
				state("handleMovement") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("action(ARG0,ARG1,ARG2,ARG3,ARG4)"), Term.createTerm("action(movimento,DESTINATION,_,_,_)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								solve("location(${payloadArg(1)},X,Y)","") //set resVar	
								forward("setGoal", "setGoal(${getCurSol("X").toString()},${getCurSol("Y").toString()})" ,"pathfinder" ) 
								solve("assert(movingTo(${payloadArg(1)}))","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
				state("assertMove") { //this:State
					action { //it:State
						solve("retract(movingTo(DEST))","") //set resVar	
						val Dest= getCurSol("DEST")
						solve("assert(done(movimento,$Dest))","") //set resVar	
						forward("actionComplete", "actionComplete(ok)" ,"butler_solver" ) 
					}
					 transition( edgeName="goto",targetState="wait", cond=doswitch() )
				}	 
			}
		}
}
