/* Generated by AN DISI Unibo */ 
package it.unibo.butler_state_handler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Butler_state_handler ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('roomState.pl')","") //set resVar	
						solve("consult('dataFunctions.pl')","") //set resVar	
						solve("showRoomState","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitAction", cond=doswitch() )
				}	 
				state("waitAction") { //this:State
					action { //it:State
					}
					 transition(edgeName="t00",targetState="handleAdd",cond=whenDispatch("handleAdd"))
					transition(edgeName="t01",targetState="handleRemove",cond=whenDispatch("handleRemove"))
					transition(edgeName="t02",targetState="handleSwap",cond=whenDispatch("handleSwap"))
				}	 
				state("handleAdd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("handleAdd(INV,NAME,CATEG)"), Term.createTerm("handleAdd(INV,NAME,CATEG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								solve("aggiungi(${payloadArg(0)},${payloadArg(1)},${payloadArg(2)})","") //set resVar	
								solve("showRoomState","") //set resVar	
								solve("assert(done(handleAdd,${payloadArg(0)},${payloadArg(1)},${payloadArg(2)}))","") //set resVar	
								forward("actionComplete", "actionComplete" ,"butler_solver" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitAction", cond=doswitch() )
				}	 
				state("handleRemove") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("handleRemove(INV,NAME,CATEG)"), Term.createTerm("handleRemove(INV,NAME,CATEG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								solve("rimuovi(${payloadArg(0)},${payloadArg(1)},${payloadArg(2)})","") //set resVar	
								solve("showRoomState","") //set resVar	
								solve("assert(done(handleRemove,${payloadArg(0)},${payloadArg(1)},${payloadArg(2)}))","") //set resVar	
								forward("actionComplete", "actionComplete" ,"butler_solver" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitAction", cond=doswitch() )
				}	 
				state("handleSwap") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("handleSwap(INV1,INV2,NAME,CATEG)"), Term.createTerm("handleSwap(INV1,INV2,NAME,CATEG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								solve("sposta(${payloadArg(0)},${payloadArg(1)},${payloadArg(2)},${payloadArg(3)})","") //set resVar	
								solve("showRoomState","") //set resVar	
								solve("assert(done(handleSwap,${payloadArg(0)},${payloadArg(1)},${payloadArg(2)},${payloadArg(3)}))","") //set resVar	
								forward("actionComplete", "actionComplete" ,"butler_solver" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitAction", cond=doswitch() )
				}	 
			}
		}
}
