/* Generated by AN DISI Unibo */ 
package it.unibo.frontend_dummy

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Frontend_dummy ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('sysRules.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitEvent", cond=doswitch() )
				}	 
				state("waitEvent") { //this:State
					action { //it:State
					}
					 transition(edgeName="t029",targetState="persistMissingFood",cond=whenDispatch("missingFood"))
					transition(edgeName="t030",targetState="persistModelContent",cond=whenDispatch("modelContent"))
				}	 
				state("persistMissingFood") { //this:State
					action { //it:State
						solve("assert(missingFood)","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitEvent", cond=doswitch() )
				}	 
				state("persistModelContent") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("modelContent(CONTENT)"), Term.createTerm("modelContent(CONTENT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								solve("assert(content(content))","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="waitEvent", cond=doswitch() )
				}	 
			}
		}
}
